'use client';

import { MouseEventHandler, } from "react";
import { useState } from "react";
import { LazyImage } from "./components/RandomFox";
import { random } from "lodash"
import Head from "next/head";

const myRandom = () => random(1, 123)


const generateId = () => Math.random().toString(36).substring(2, 9)

export default function Home() {
  const [images, setImages] = useState<Array<IFoxImageItem>>([])

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (e) => {
    e.preventDefault()

    const newImageItem: IFoxImageItem = { id: generateId(), url: `https://randomfox.ca/images/${myRandom()}.jpg` }
    setImages([
      ...images,
      newImageItem
    ])

    window.plausible("SignUp")
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          defer
          data-domain="yourdomain.com"
          src="https://plausible.io/js/script.js"
        ></script>
      </Head>

      <header className="pt-10 pb-4 px-4 sm:px-6 lg:px-8 grid place-items-center mb-5">
        <p className="text-2xl leading-6 font-semibold tracking-wide  text-orange-500">
          Lazy Image Component
        </p>
        <div className="max-w-lg mx-auto text-md  leading-7">
          <p className="mt-4">
            A generic React component to load images with lazy loading.
          </p>
          <p className="mt-4">
            ✨✨ Added images will not be downloaded until they are visible on the screen.✨✨
          </p>
        </div>
      </header>

      < main >
        <button
          className="block mx-auto py-3 px-6 rounded-full bg-orange-500 font-bold cursor-pointer shadow-lg shadow-orange-500/50 hover:bg-orange-600"
          onClick={addNewFox}>Add new fox
        </button>

        {images.map(({ id, url }, index) => (
          <div key={id} className="p-4 grid place-items-center">
            <LazyImage
              className="rounded-lg  bg-gray-300"
              width={320}
              height="auto"
              title={`Random Fox #${index + 1}`}
              src={url}
              onClick={() => console.log("hey")}
            />
          </div>
        ))}
      </main >
      <footer >

      </footer>
    </div >
  );
}
